--INSERT INTO articulos (nombre, descripcion, precio) values ("Producto 1", "Producto 1 Descripcion", 5000)
--INSERT INTO articulos (nombre, descripcion, precio) values ("Producto 2", "Producto 2 Descripcion", 3000)
--INSERT INTO articulos (nombre, descripcion, precio) values ("Producto 3", "Producto 3 Descripcion", 5400)